# Generated by Django 4.2.4 on 2023-08-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.CharField(blank=True, null=True),
        ),
    ]
