# Generated by Django 4.2.4 on 2023-08-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_delete_productview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
